# Generated by Django 5.0.1 on 2024-01-24 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='visitaor',
            new_name='visitor',
        ),
    ]
